version: '3.4'

services:
  datametrics.api.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro