global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'datametrics-prometheus'
    metrics_path: '/metrics-text'
    static_configs:
    - targets: 
      - 'datametrics.api.host:80'